# fly.toml app configuration file generated for mapleutils-mirror on 2023-08-26T05:30:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "mapleutils-mirror"
primary_region = "ord"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
